version: '2'

services:
  product:
    image: product
    build: ""
    container_name: product
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=product_db
      - DATABASE_USER=compose-postgres
      - DATABASE_PASSWORD=compose-postgres
    depends_on:
      - db
  db:
    restart: always
    image: 'postgres:13.1-alpine'
    container_name: product_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
## to access your db from docker cli psql -U compose-postgres product_db