version: '2'

services:
  db:
    restart: always
    image: 'postgres:13.1-alpine'
    container_name: product_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  product:
    image: product
    build: .
    container_name: product
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_NAME=product_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - "db"
## to access your db from docker cli psql -U postgres product_db
# netstat -ano | findstr :5432
# taskill /PID <ID> /F